site_name: My Analysis Results
site_description: Jupyter notebook analysis and interactive figures
repo_url: https://github.com/yourusername/yourrepo

theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    # - navigation.indexes
    # - content.tabs.link
    # - navigation.expand    # Expand by default (optional, remove if you want all closed)

plugins:
  - search
  - mkdocs-jupyter:
      # include_source: True
      ignore_h1_titles: True
  # - macros
  - awesome-pages

nav:
  - Home: index.md
  - Analysis:
    - Cell Summaries:
      - Default: analysis/cell-summaries/default.ipynb
      - Naive Reversions First: analysis/cell-summaries/naive_reversions_first.ipynb
      - Naive Reversions No BP: analysis/cell-summaries/naive_reversions_no_bp.ipynb
    - Fitness Regression:
      - Default: analysis/fitness-regression/default.ipynb
      - Naive Reversions First: analysis/fitness-regression/naive_reversions_first.ipynb
      - Naive Reversions No BP: analysis/fitness-regression/naive_reversions_no_bp.ipynb
    - Mutations:
      - Default: analysis/mutations/default.ipynb
      - Naive Reversions First: analysis/mutations/naive_reversions_first.ipynb
      - Naive Reversions No BP: analysis/mutations/naive_reversions_no_bp.ipynb
    - NDS-LB:
      - Default: analysis/NDS-LB/default.ipynb
      - Naive Reversions First: analysis/NDS-LB/naive_reversions_first.ipynb
      - Naive Reversions No BP: analysis/NDS-LB/naive_reversions_no_bp.ipynb
  - Interactive Figures: 
    - Mutation Heatmaps: 
      - Default: interactive-figures/mutation-heatmaps/default.html
      - Naive Reversions First: interactive-figures/mutation-heatmaps/naive_reversions_first.html
      - Naive Reversions No BP: interactive-figures/mutation-heatmaps/naive_reversions_no_bp.html
  #   - Overview: figures/overview.md
    # Add specific figure pages here

# extra_javascript:
#   - javascripts/extra.js