[project]
authors = ["jgallowa07 <jaredgalloway07@gmail.com>"]
channels = ["conda-forge"]
name = "gcreplay"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
git-lfs = ">=3.6.1,<4"
pandas = ">=2.2.3,<3"

[pypi-dependencies]
mkdocs = "*"
mkdocs-material = "*"
mkdocs-jupyter = "*"
mkdocs-macros-plugin = "*"
mkdocs-awesome-pages-plugin = "*"
