[project]
authors = ["jgallowa07 <jaredgalloway07@gmail.com>"]
channels = ["conda-forge"]
name = "gcreplay"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
git-lfs = ">=3.6.1,<4"
pandas = ">=2.2.3,<3"
biopython = ">=1.85,<2"
regex = ">=2024.11.6,<2025"
matplotlib = ">=3.9.4,<4"

[pypi-dependencies]
mkdocs = "*"
mkdocs-material = "*"
mkdocs-jupyter = "*"
mkdocs-macros-plugin = "*"
mkdocs-awesome-pages-plugin = "*"
ete3 = ">=3.1.3, <4"
