# Use the mambaforge base image
FROM quay.io/condaforge/mambaforge

# For this to work with a singularity wrapper
# we have top move it somewhere other than root
# ENV PATH="/opt/miniconda3/bin:${PATH}"
# ARG PATH="/opt/miniconda3/bin:${PATH}"

# use apt get to install poppler-utils
RUN apt-get update && apt-get install -y poppler-utils

# Set environment name
ENV ENV_NAME=replay
# this is to avoid the fact that apptainer cannot access the default /tmp directory
ENV MPLCONFIGDIR=/tmp/matplotlib
RUN mkdir -p /tmp/matplotlib && chmod -R 777 /tmp/matplotlib

# Create and configure the environment
RUN mamba create -n $ENV_NAME -y \
    -c bioconda \
    -c conda-forge \
    seaborn \
    altair \
    biopython \
    pandas \
    jupyter \
    scikit-learn \
    svgutils \
    gctree==4.3.0 \
    papermill \
    openpyxl \
 && mamba clean -afy

# Ensure the environment is activated by default
RUN echo "conda activate $ENV_NAME" >> ~/.bashrc
ENV PATH /opt/conda/envs/replay/bin:$PATH

RUN python -m pip install pdf2image piecewise_regression

# Set the working directory
WORKDIR /workspace

# Define the default command for the container
ENTRYPOINT ["/bin/bash"]
