name: Build and Deploy Notebook Site

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.42.1
          cache: true

      - name: Install dependencies with Pixi
        run: |
          pixi install

      - name: Build Docs with MkDocs
        run: |
          pixi run mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './site'  # Adjust this to your build output directory
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

